#!/usr/bin/env bash
# pinging an IP address passed as an argument

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [ $# -gt 1 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1" -c 5
fi
